main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.user_login, name='login'),
    path('signup', views.user_signUp, name='signup'),
    path('logout', views.logout_user, name='logout'),
]

remake_story9/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm



def home(request):
    return render(request, 'main/home.html')


def user_login(request) :
    if request.user.is_authenticated:
        return redirect('main:home')
    if request.method == "POST" :
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:home')
        else :
            context = {'failed': 'please check your username or password'}
            return render(request, 'main/login.html', context)
    return render(request, 'main/login.html')

def user_signUp(request) :
    form = UserCreationForm()
    if request.user.is_authenticated:
        return redirect('main:home')

    if request.method == "POST" :
        form = UserCreationForm(request.POST)
        if form.is_valid() :
            form.save()
            new_user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'],)
            login(request, new_user)
            return redirect('main:login')

    context = {'form' : form}
    return render(request, 'main/signup.html', context)

def logout_user(request) :
    logout(request)
    return redirect('main:home')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>

<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

{% endblock meta %}

{% block content %}
  
  {% if user.is_authenticated %}
    <div class="container-fluid text-center" style="background-color:#353535 ; min-height: 100vh;">
      <div class="row justify-content-center" >
        <div class="col-12" style="text-align: center; padding-top:10%; ">
          <h1 style="color: #EFEFEF;">Hello, {{user.username}}</h1>
          <p style="color: #EFEFEF;">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
            Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
            Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </p>
        </div>
      </div>
      <a href="{%url 'main:logout' %}" class="btn btn-outline-light" style="margin-left: 2rem;">Log Out</a>
    </div>

  {%else%}
  <div class="container-fluid text-center" style="background-color:#353535 ; min-height: 100vh;">
    <div class="row justify-content-center" >
      <div class="col-12" style="text-align: center; padding-top:10%; ">
        <h1 style="color: #EFEFEF; padding-top: 5rem;">Please Login</h1>
        <div class="separator" style="padding-top: 3rem;">
          <a href="{%url 'main:login' %}" class="btn btn-outline-light" style="padding-right: 20px; padding-left: 20px;">Login</a>
          <a href="{%url 'main:signup' %}" class="btn btn-outline-light" style="margin-left: 2rem;">Sign Up</a>
        </div>
      </div>
    </div>
  </div>

  {% endif %}

{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>

<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

{% endblock meta %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="container-fluid text-center" style="background-color: #353535; min-height: 100vh;">
        <div class="row">
            <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
                <h1 style="color: #EFEFEF">Login</h1>
            </div>
        </div>
        <div class="border border-light" style="padding: 5%; margin:5% auto; width: 400px;">
            {% if failed %}
            <div class="alert alert-danger" role="alert">
                <p class=lead style='font-size:small; margin-bottom: 0;'> invalid username or password! </p> 
            </div>
            {% endif %}
            <div class="row justify-content-center form-group ">
                <div class=col-12>
                    <label for="username" style="color: #EFEFEF">Username:</label><br>
                    <input type="text" class="form-control" name="username"><br>
                    <label for="password" style="color: #EFEFEF">Password:</label><br>
                    <input type="password" class="form-control" name="password"> <br>
                    <button type="submit" name="login" value="login" class="btn btn btn-outline-light btn-block" style="margin-top: 2rem;">Login</button>
                </div>                
            </div>
        </div>

        
    </div>
</form>


{% endblock content %}

main/templates/main/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block meta %}
<title>Story 9</title>

<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1cQRFi3dgfSVKpc1B9idTEuN3cBScszNHP9silYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

{% endblock meta %}

{% block content %}

<form action="" method="POST">
  {% csrf_token %}
  <div class="container text-center">
    <div class="row">
        <div class='col col-md-12' style="padding-top:5%; padding-bottom: 0px;">
          <h1 style="padding-top: 1rem;">Sign Up</h1>
        </div>
    </div>
    <div class="border border-dark" style="padding: 5%; margin:5% auto; width: 600px;">
      {% if failed %}
        <div class="alert alert-danger" role="alert">
          <p class=lead style='font-size:small; margin-bottom: 0;'> invalid username or password! </p> 
        </div>
      {% endif %}
      <div class="row justify-content-center form-group">
        <div class=col-12>
          {{form | crispy}}
          <button type="submit" name="signup" value="signup" class="btn btn-outline-dark btn-block">Login</button>
        </div>                
      </div>
    </div>
  </div>
</form>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>